In [2]:
import numpy as np

### Scalar

In [3]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

## Vector

In [4]:
x = np.array([42,23,453,21,32,1,3,7])
print(x.shape)
x.ndim

(8,)


1

## Matrix

In [6]:
x = np.array([[42,23,453],
             [34,343,24]])
print(x.shape)
print(x.size)
x.ndim

(2, 3)
6


2

## Tensor

In [7]:
x = np.array([[[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]]])
print(x.shape)
print(x.size)
x.ndim

(4, 2, 3)
24


3

## Reshape

In [8]:
x = np.array([[0,1],
             [2,3],
             [4,5],
             [6,7]])
print(x.size)
x.shape

8


(4, 2)

In [ ]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])